language: python
os: linux
dist: xenial
python:
  - 3.7
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install email-validator
  - pip install coverage
  - pip install Flask-Script
  - pip install Flask-Bcrypt
  - pip install Flask-Cors
  - pip install Flask-User
  - pip install Flask-Testing
  - pip install flask-jwt-extended
# command to run tests
script: python3 manage.py test || python manage.py test