language: python
os: osx
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install email-validator
  - pip install coverage
  - pip install Flask-Script
  - pip install Flask-Bcrypt
  - pip install Flask-Cors
  - pip install jwt
  - pip install Flask-User
  - pip install Flask-Testing
  - pip install flask-jwt-extended
# command to run tests
script: python3 manage.py test || python manage.py test