"""empty message

Revision ID: 1424f87aebf7
Revises: b8934f704d53
Create Date: 2020-09-10 14:22:36.615858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1424f87aebf7'
down_revision = 'b8934f704d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('body', sa.String(length=100), nullable=False),
    sa.Column('colour', sa.String(length=30), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('cost_per_hour', sa.Float(), nullable=False),
    sa.Column('manu_date', sa.DateTime(), nullable=True),
    sa.Column('calendar_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('calendar_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
