"""empty message

Revision ID: 3b3e6197f4b5
Revises: b38c4b860656
Create Date: 2020-08-28 16:54:37.722979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b3e6197f4b5'
down_revision = 'b38c4b860656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('email_confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(length=100), server_default='', nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=100), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'email_confirmed_at')
    op.drop_table('user_roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
