"""empty message

Revision ID: 618a2c883514
Revises: 7e871957362c
Create Date: 2020-09-08 18:42:36.149959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618a2c883514'
down_revision = '7e871957362c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('calendar_id', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'calendar_id')
    # ### end Alembic commands ###
