"""empty message

Revision ID: 61f07127a7c4
Revises: f0258911b2db
Create Date: 2020-09-22 05:41:00.008853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61f07127a7c4'
down_revision = 'f0258911b2db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('status', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'history', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history', type_='unique')
    op.drop_column('cars', 'status')
    # ### end Alembic commands ###
