"""empty message

Revision ID: 6c4e967bbddc
Revises: 1424f87aebf7
Create Date: 2020-09-17 09:54:11.476952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4e967bbddc'
down_revision = '1424f87aebf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cars', ['name'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'cars', type_='unique')
    # ### end Alembic commands ###
