"""empty message

Revision ID: 7e871957362c
Revises: 3d9684fbe149
Create Date: 2020-09-02 08:08:25.112240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e871957362c'
down_revision = '3d9684fbe149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['email'], ['users.email'], name='admins_email_fkey'),
    sa.PrimaryKeyConstraint('email', name='admins_pkey')
    )
    # ### end Alembic commands ###
