"""empty message

Revision ID: a3767c2a6f6f
Revises: 618a2c883514
Create Date: 2020-09-08 18:50:29.253787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3767c2a6f6f'
down_revision = '618a2c883514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('calendar_id', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'calendar_id')
    # ### end Alembic commands ###
