"""empty message

Revision ID: b38c4b860656
Revises: 
Create Date: 2020-08-26 09:15:41.275745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b38c4b860656'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('body', sa.String(length=100), nullable=False),
    sa.Column('colour', sa.String(length=30), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('cost_per_hour', sa.Float(), nullable=False),
    sa.Column('manu_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_table('cars')
    # ### end Alembic commands ###
