"""empty message

Revision ID: b8934f704d53
Revises: fcb35d35b04b
Create Date: 2020-09-08 19:40:33.777482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8934f704d53'
down_revision = 'fcb35d35b04b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('calendar_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'cars', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cars', type_='unique')
    op.drop_column('cars', 'calendar_id')
    # ### end Alembic commands ###
