"""empty message

Revision ID: bd82fb71c9d8
Revises: a3767c2a6f6f
Create Date: 2020-09-08 18:52:10.482577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd82fb71c9d8'
down_revision = 'a3767c2a6f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('calendar_id', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'calendar_id')
    # ### end Alembic commands ###
