"""empty message

Revision ID: f0258911b2db
Revises: 6c4e967bbddc
Create Date: 2020-09-21 07:45:38.929097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0258911b2db'
down_revision = '6c4e967bbddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('car', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('rent_date', sa.DateTime(), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=False),
    sa.Column('verify_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('car'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    # ### end Alembic commands ###
