"""empty message

Revision ID: fcb35d35b04b
Revises: bd82fb71c9d8
Create Date: 2020-09-08 18:58:23.161230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb35d35b04b'
down_revision = 'bd82fb71c9d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('calendar_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cars', 'calendar_id')
    # ### end Alembic commands ###
